from database import databaseNHL

engine = databaseNHL.connect_to_db()

engine.execute("CREATE TABLE IF NOT EXISTS team_table(team_id TEXT, team_name TEXT, team_abbr TEXT, franchise_id TEXT, league TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS player_table(player_id TEXT, f_name TEXT, l_name TEXT,  team_id TEXT, role TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS schedule(game_id TEXT, game_datetime TEXT, away_name TEXT, home_name TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS game_table(game_id TEXT, game_date TEXT, away_team TEXT, home_team TEXT, away_score TEXT, home_score TEXT, winner TEXT, season_id TEXT, state TEXT, start_time TEXT, import_state TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS updates(update_id TEXT, update_date TEXT, update_time TEXT, last_record TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS skater_stats(game_id TEXT, player_id TEXT, team_side TEXT,  plus_mius TEXT, penalty_minutes TEXT, assists TEXT, time_on_ice TEXT, fenwick_for_percent_relative TEXT, corsi_for TEXT, position TEXT, goals TEXT, points TEXT, corsi_against TEXT, fenwick_for_percent TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS goaltender_stats(game_id TEXT, player_id TEXT, team_side TEXT,  penalty_minutes TEXT, time_on_ice TEXT, position TEXT, save_percentage TEXT, goals_against TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS model_input(game_id TEXT, start_time TEXT, player_id TEXT,  position TEXT, plays_for_home_team TEXT, home_team_won TEXT, total_games TEXT, is_goaltender TEXT, is_forward TEXT, weighted_average_goals TEXT, weighted_average_assists TEXT, weighted_average_points TEXT, weighted_average_plus_minus TEXT, weighted_average_penalty_minutes TEXT, weighted_average_time_on_ice TEXT, weighted_average_corsi_for TEXT, weighted_average_corsi_against TEXT, weighted_average_fenwick_for_percent TEXT, weighted_average_fenwick_for_percent_relative TEXT, weighted_average_save_percentage TEXT, weighted_average_goals_against TEXT, recent_form_goals TEXT, recent_form_assists TEXT, recent_form_points TEXT, recent_form_plus_minus TEXT, recent_form_penalty_minutes TEXT, recent_form_time_on_ice TEXT,recent_form_corsi_for TEXT, recent_form_corsi_against TEXT, recent_form_fenwick_for_percent TEXT, recent_form_fenwick_for_percent_relative TEXT, recent_form_save_percentage TEXT, recent_form_goals_against TEXT, current_game_position TEXT, current_game_goals TEXT, current_game_assists TEXT, current_game_points TEXT, current_game_plus_minus TEXT, current_game_penalty_minutes TEXT, current_game_time_on_ice TEXT, current_game_corsi_for TEXT, current_game_corsi_against TEXT, current_game_fenwick_for_percent TEXT, current_game_fenwick_for_percent_relative TEXT, current_game_save_percentage TEXT, current_game_goals_against TEXT);")
engine.execute("CREATE TABLE IF NOT EXISTS predictions(game_id TEXT, model_type TEXT, away_team TEXT, home_team TEXT);")
